## Esempio del workflow intero. 
## Da modificare con i percorsi corretti

cd X7645_lane1

bash /home/comparazione_kit/calcolo_identità_sequenze_Sequenziatori/trim_adapters_only_and_mapBWA2.sh X7645_lane1_L1_R1.fastq.gz X7645_lane1_L1_R2.fastq.gz 20

cd /home/comparazione_kit/calcolo_identità_sequenze_Sequenziatori/Element_WGS/RUN_4

bash /home/comparazione_kit/calcolo_identità_sequenze_Sequenziatori/Run_Identity_Workflow.sh X7645_lane1/start_sorted.bam /home/comparazione_kit/calcolo_identità_sequenze_Sequenziatori/HG001_GRCh38_1_22_v4.2.1_benchmark.vcf.gz NA12878_Element_run4_GIAB > IDENTITY_NA12878_Element_run4_GIAB.log

bash /home/comparazione_kit/calcolo_identità_sequenze_Sequenziatori/Run_Identity_Workflow_read_Q30_up.sh X7645_lane1/start_sorted.bam /home/comparazione_kit/calcolo_identità_sequenze_Sequenziatori/HG001_GRCh38_1_22_v4.2.1_benchmark.vcf.gz NA12878_Element_run4_GIAB_reads_Q30_up > IDENTITY_NA12878_Element_run4_GIAB_reads_Q30_up.log